# -*- coding: utf-8 -*-
"""calculo_idade.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DADGaUGNTuG5NE5xl5HblMWLhAgQ_uGs
"""

idade = -1
while (idade == -1):
  try:
    nome = input("Insira seu nome completo: ")
    ano_nascimento = int(input("Em qual ano você nasceu? "))

    if (ano_nascimento < 1922 or ano_nascimento > 2021):
      print("Digite um ano entre 1922 e 2021!")
      print()
    else:
      idade = 2022 - ano_nascimento
      print(f"{nome}, você completou ou completará {idade} anos este ano.")
  except:
    print("Digite um ano entre 1922 e 2021!")
    print()




"""
Desenvolva um programa que recebe do usuário nome completo e ano de nascimento
que seja entre 1922 e 2021. A partir dessas informações, o sistema mostrará o
nome do usuário e a idade que completou, ou completará, no ano atual (2022).
Caso o usuário não digite um número ou apareça um inválido no campo do ano, 
o sistema informará o erro e continuará perguntando até que um valor correto
seja preenchido.
"""
